### ISSUE TITLE
can't compile on Ubuntu 16.04 fresh install

### ISSUE THREAD

**Issue by mcamurri** [oxfordrobotics/drs-externals#2]
I'm having an issue compiling the repository on a new machine: 
```
~/legacy_pods/libbot/bot2-vis/pod-build/lib/libbot2-vis.so: error: undefined reference to 'XOpenDisplay'
~/legacy_pods/libbot/bot2-vis/pod-build/lib/libbot2-vis.so: error: undefined reference to 'XFree'
~/legacy_pods/libbot/bot2-vis/pod-build/lib/libbot2-vis.so: error: undefined reference to 'XVisualIDFromVisual'
~/legacy_pods/libbot/bot2-vis/pod-build/lib/libbot2-vis.so: error: undefined reference to 'XGetVisualInfo'
```

Is there a missing dependency? I couldn't find a README with pre-requisites.

Note that I've commented out the tobuild.txt of the repo to include only as follows:

- bot_core_lcmtypes
- libbot
- occ-map
- common_utils

and the common_utils to include only:

- concise-args
- stl-utils
- path-util
- eigen-utils

This works on another machine I've already set up.

**Comment by mauricefallon** [comment]
i cant reply now, but does this help:
https://github.com/ashuang/libbot
https://github.com/libbot2/libbot2
its the upstream source of libbot

**Comment by mcamurri** [comment]
I've solved the problem by explicitly adding X11 to the target libraries.

**Note:** the commit of libbot this repo is pointing to is pretty old. It does not include [my previous bugfix](https://github.com/openhumanoids/libbot/commit/88fe6828d5b2cfb4d144a28251cba5cfa1a9f5eb).

I've created a [merge request](https://github.com/openhumanoids/libbot/pull/8) on top of [`libbot-openhumanoids`](https://github.com/openhumanoids/libbot/tree/libbot-openhumanoids) and not [`mf-revert-double-pane-on-gtk-viewer`](https://github.com/openhumanoids/libbot/tree/mf-revert-double-pane-on-gtk-viewer) as it is pointing right now.

This change has to be coupled with [its counterpart in common_utils.](https://github.com/openhumanoids/common_utils/pull/14)
